### ISSUE TITLE
`stable_cumsum` needs to be imported

### ISSUE THREAD

**Issue by sayakpaul** [hendrycks/natural-adv-examples#5]
`stable_cumsum` https://github.com/hendrycks/natural-adv-examples/blob/07770705658c3a1c8acce31fd9dbd68f06e297c3/calibration_tools.py#L144 needs to be imported.

**Comment by matteoguarrera** [comment]
The function should be this one: https://github.com/wetliu/energy_ood/blob/7d31247d980b5337c519a61402d35141f5ec6289/utils/display_results.py
Have fun!

**Comment by sayakpaul** [comment]
Thank you.
